FROM node:20

# Install Amplify CLI globally
RUN npm install -g @aws-amplify/cli

# Set the working directory
WORKDIR /chatbot

# Set the default command to run when the container starts
CMD ["/bin/bash"]